/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvestmentsIndexRouteImport } from './routes/investments.index'
import { Route as InvestmentsSlugRouteImport } from './routes/investments.$slug'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsIndexRoute = InvestmentsIndexRouteImport.update({
  id: '/investments/',
  path: '/investments/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsSlugRoute = InvestmentsSlugRouteImport.update({
  id: '/investments/$slug',
  path: '/investments/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/news': typeof NewsRoute
  '/team': typeof TeamRoute
  '/investments/$slug': typeof InvestmentsSlugRoute
  '/investments/': typeof InvestmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/news': typeof NewsRoute
  '/team': typeof TeamRoute
  '/investments/$slug': typeof InvestmentsSlugRoute
  '/investments': typeof InvestmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/news': typeof NewsRoute
  '/team': typeof TeamRoute
  '/investments/$slug': typeof InvestmentsSlugRoute
  '/investments/': typeof InvestmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/news'
    | '/team'
    | '/investments/$slug'
    | '/investments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/news'
    | '/team'
    | '/investments/$slug'
    | '/investments'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/news'
    | '/team'
    | '/investments/$slug'
    | '/investments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  NewsRoute: typeof NewsRoute
  TeamRoute: typeof TeamRoute
  InvestmentsSlugRoute: typeof InvestmentsSlugRoute
  InvestmentsIndexRoute: typeof InvestmentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments/': {
      id: '/investments/'
      path: '/investments'
      fullPath: '/investments/'
      preLoaderRoute: typeof InvestmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments/$slug': {
      id: '/investments/$slug'
      path: '/investments/$slug'
      fullPath: '/investments/$slug'
      preLoaderRoute: typeof InvestmentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  NewsRoute: NewsRoute,
  TeamRoute: TeamRoute,
  InvestmentsSlugRoute: InvestmentsSlugRoute,
  InvestmentsIndexRoute: InvestmentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
